apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tool-services-paa-scaling
  namespace: dataxquare-tool
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tool-services-paa
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 45