# API Configuration file

swagger: "2.0"

info:
  title: PAA
  version: "1.0.3"
  description: Simple API to retrieve PAA

paths:
  /paa:
    post:
      description: returns PAA of google
      operationId: app.paa
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          description: data to use for paa
          schema:
            type: object
            required:
              - keyword
              - hl
              - gl
            properties:
              keyword:
                type: string
              hl:
                type: string
              gl:
                type: string
      responses:
        200:
          description: Succesfull request
          schema:
            type: array
            items:
              type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/DefaultError'
definitions:
  DefaultError:
    type: object
    required:
      - code
      - message
    properties:
      message:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600
