name: Create and publish a Docker image on releases

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Log in to Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: 7j3k22hp.gra7.container-registry.ovh.net
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Give script permissions
        run: chmod +x ./build.sh

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.3.0
        with:
          images: 7j3k22hp.gra7.container-registry.ovh.net/tool/services/paa
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        shell: bash
        run: ./build.sh --release ${{ steps.meta.outputs.version }}